	<div class="clear" id="footer"> <!-- Start Footer -->
		<p>&copy; 2004 Novell, Inc. All Rights Reserved<br>
		Novell is a registered trademark and Mono is a trademark of Novell, Inc. in the United States and other countries.  All third-party trademarks are the property of their respective owners.</p>

	<p>
		<a href="http://jigsaw.w3.org/css-validator/check/referer"><img style="border:0;width:88px;height:31px" src="/img/vcss.png" alt="Valid CSS!"></a>
		<!-- a href="http://validator.w3.org/check?uri=referer"><img border="0" src="/img/valid-html401.png" alt="Valid HTML 4.01!" height="31" width="88"></a -->
	</p>
	<script language="javascript1.2" type="text/javascript" src="http://www.novell.com/inc/superstats.js"></script>

	</div> <!-- End Footer -->