<!-- NOTE: Closing li must have a space before it if it is not on a new line by itself. -->
					<ul id="menu">
						<li>Quick Start
							<ol>
								<li><a href="/using/index.html">Installing Mono</a></li>
								<li><a href="/using/runningfirstmonoapp.html">Running Mono</a></li>
								<li><a href="/using/macos.html">Mono on MacOS X</a></li>
							</ol>
						</li>
						<li>Developing with Mono
							<ol>
								<li><a href="/using/monodevelop.html">IDE for Mono</a> </li>
								<li><a href="/using/jit-debug.html">Debugging Applications</a></li>
								<li><a href="http://primates.ximian.com/~edasque/projects/Tutorial/glade2.html">Mono and Gtk# Tutorials</a></li>
								<li><a href="/using/runtime.html">The Mono Runtime</a></li>
								<li><a href="/using/embedded-api.html">Embedding Mono</a></li>
								<li><a href="http://www.go-mono.com/docs">Overall API Docs</a></li>
							</ol>
						</li>
						<li><a href="/using/bugs.html">Bug Reporting</a></li>
					</ul>