<!-- NOTE: Closing li must have a space before it if it is not on a new line by itself. -->
					<ul id="menu">
						<li><a href="/about/index.html">What is Mono?</a> </li>
						<!--li><a href="/about/whymono.html">Why Mono?</a> </li>-->
						<li><a href="/about/mono-roadmap.html">Mono Roadmap</a> </li>
						<li><a href="/about/applications.html">Screenshots</a> </li>
						<li>FAQ
							<ol>
   							    <li><a href="/about/faq.html">General</a></li>
								<li><a href="/about/technical.html">Technical Questions</a></li>
								<li><a href="/about/licensing.html">Licensing and Patents</a></li>
							</ol>
						</li>
						<li>Resources
							<ol>
								<li><a href="http://forge.novell.com/modules/xfmod/newsportal/?group_id=1300">Forums</a></li>
								<li><a href="/about/mailing-lists.html">Mailing Lists</a></li>
							<!--	<li><a href="/news/monologue.html">Blogs</a></li> -->
								<li><a href="/about/books.html">Books</a></li>
								<li><a href="/about/relatedsites.html">Related Sites</a></li>
								<li><a href="/about/papers.html">Papers</a></li>
								<li><a href="/about/irc.html">IRC</a></li>
								<li><a href="/about/team.html">Mono Team</a></li>
								<li><a href="/about/logos.html">Logos</a></li>
							</ol>
						</li>
						<li><a href="http://www.go-mono.com/monologue/">Blogs</a></li>
						<li><a href="/downloads/">Downloads</a></li>
					</ul>