<!-- NOTE: Closing li must have a space before it if it is not on a new line by itself. -->
					<ul id="menu">
						<li>Getting Started
							<ol>
								<li><a href="/contributing/getting-started.html">Contributing to Mono</a></li>
								<li><a href="/contributing/anonsvn.html">SVN Checkouts</a></li>
								<li><a href="/contributing/compiling.html">Compiling</a></li>
								<li><a href="/contributing/todo.html">Todo</a></li>
								<li><a href="/contributing/resources.html">Resources</a></li>
								<li><a href="/contributing/testing.html">Tools - Test Suite</a></li>
			<!--					<li><a href="/contributing/mono-contribution-howto.html">Tools - Howto info</a></li>
								<li><a href="javascript:void(0)">Patch acceptance policy</a></li>-->
								<li><a href="/contributing/svnwrite.html">SVN Write Access</a></li>
								<li><a href="/contributing/hall.html">Hall of Fame</a></li>
								

							</ol>
						</li>
						<li>Porting and Hardware Architecture
							<ol>
								<li><a href="/contributing/ppc.html">PowerPC</a></li>
							</ol>
						</li>
						<li>Writing Docs
							<ol>
								<li><a href="/contributing/classlib-doc.html">Class Docs</a></li>
							</ol>
						</li>
						<li>Roadmap and Plans
							<ol>
								<li><a href="/contributing/plans.html">Plans</a></li>
								<li><a href="/contributing/winforms.html">Windows.Forms</a></li>
								<li><a href="/contributing/db4o.html">db4objects</a></li>
								<li><a href="/contributing/mysql.html">DB - MySQL</a></li>
								<li><a href="/contributing/ibmdb2.html">DB - IBM DB2</a></li>
								<li><a href="/contributing/firebird.html">DB - Firebird Interbase</a></li>
								<li><a href="/contributing/sqlclient.html">DB - MS SQL</a></li>
								<li><a href="/contributing/odbc.html">DB - ODBC</a></li>
								<li><a href="/contributing/oledb.html">DB - OLE DB</a></li>
								<li><a href="/contributing/oracle.html">DB - Oracle</a></li>
								<li><a href="/contributing/sybase.html">DB - Sybase</a></li>
								<li><a href="/contributing/sqlite.html">DB - SQL Lite</a></li>
								<li><a href="/contributing/postgresql.html">DB - PostgreSQL</a></li>
								<li><a href="/contributing/tdsclient.html">DB - TDS Generic</a></li>
								<li><a href="/contributing/drawing.html">Drawing</a></li>
								<li><a href="/contributing/ado-net.html">ADO.NET</a></li>
								<li><a href="/contributing/provider-factory.html">ProviderFactory</a></li>
								<li><a href="/contributing/tds-providers.html">TDS Providers</a></li>
								<li><a href="/contributing/crypto.html">Crypto</a></li>
								<li><a href="/contributing/java.html">Java</a></li>
								<li><a href="/contributing/xml-classes.html">XML</a></li>
							</ol>
						</li>
					</ul>
