		<div id="rightNav"> <!-- Start Right Nav -->
				<h1>In The News</h1>
				<ul>
					<li><a href=""><b>19 Dec 2004:</b><br>
					Editor's Choice Award</a></li>

					<li><b>31 May 2004:</b><br>
					CLI Integration</li>

					<li><b>22 May 2004:</b><br>
					Mono 1.0 plans</li>

					<li><b>14 May 2004:</b><br>
					Whither Mono</li>

					<li><b>00 Dec 2004:</b><br>
					The penguin takes flight</li>
				</ul>

				<h1>Mono Status</h1>
				<ul>
					<li><b>C# Compiler:</b><br>
					Self hosting on Linux and .NET</li>
					<li><b>JIT:</b><br>
					Works for Linux/86</li>
					<li><b>Interpreter:</b><br>
					Works for Linux/86, Linux/PPC, S390, StrongARM, SPARC, HPPA, SPARC v9</li>
					<li><b>ASP.NET:</b><br>
					Webforms and WebServices working</li>
				</ul>
		</div> <!-- End Right Nav -->
