		<div id="rightNav"> <!-- Start Right Nav -->
			<div id="rightNavTop"><!-- Comment is here to fix an IE DIV height display bug. jduncan --></div>
			<div id="rightNavBlue">
				<h1>In The News</h1>
			<ul>
<li>
		
			<b>Mono 1.0 launch press coverage</b>
		
		<br>
			<a href="/news/mono1.0.press.html ">July 2004<br> Mono 1.0 covered in more than 45 articles</a>
		
	</li>

<li>
		
			<b>Mono 1.0 Released !</b>
		
		<br>
			<a href="http://www.mono-project.com/using/relnotes/1.0.html">June 30th,2004<br>Release Notes</a>
		
	</li>

<li>
		
			<b>Previous Press Coverage</b>
		
		<br>
			<a href="/news/monoBeta1_press.html">May 2004<br> Mono Beta 1 rallies the press</a>
		
	</li>
 	 <li>
	      <b>Linux Planet</b><br>   
	      <a href="http://www.linuxplanet.com/linuxplanet/reports/5375/4/">May 3rd, 2004<br>And then there's Mono</a>
	  </li>
<p>
	  <li>
	    
	      <b>DevChannel</b><br>
	    
	    
	      <a href="http://tools.devchannel.org/devtoolschannel/04/04/21/169234.shtml?tid=46">Apr 26th, 2004<br>What is Mono and why should you care ?</a>
	    
</li>
	  <li>
	    
	
	    
	      <b>OSDir.com</b><br>
	      <a href="http://osdir.com/Article198.phtml">Dec 19th, 2003<br> Editor's Choice Award.</a>
	    
	  </li>

<!--
	  <li>
	    

	    
	     <b>InforWorld</b><br>
	      <a href="http://www.infoworld.com/article/03/05/22/HNmono_1.html">May 22nd, 2003</a><br>Mono 1.0 plans.
	    
	  </li>
	  <li>
	    
	
	    
	     <b>InfoWorld</b><br>
	      <a href="http://www.infoworld.com/article/03/03/14/11sliatdev_1.html">Mar 14th, 2003</a><br>Whither Mono?
	    
	  </li>
	  <li>
	    
	
	     <b>InfoWorld</b><br>
	    
	      <a href="http://www.infoworld.com/article/03/05/22/HNmono_1.html">Dec, 2002</a><br>The Penguin takes flight.
	    
	  </li> -->
				</ul>
			</div>
		</div> <!-- End Right Nav -->
