		<div id="rightNav"> <!-- Start Right Nav -->
			<div id="rightNavTop"><!-- Comment is here to fix an IE DIV height display bug. jduncan --></div>
			<div id="rightNavGreen">
				<h1>Mono Status</h1>
				<ul>
					<li><a href="/using/mcs.html"><b>C# Compiler:</b></a><br>
					Self hosting on Linux and .NET<br>
					Compliant with ECMA #334 for C# 1.0.
				        C# 2.0 features previewed in <i>gmcs</i></li>

					<li><b>32-bit JIT:</b><br>
					Works for Linux/86, Linux/PPC, Solaris/SPARC
					S390 and MacOS X</li>

					<li><b>64-bit JIT:</b><br>
					Linux/x86-64, Solaris/SPARCv9.  Mono 1.1 only.
					</li>

					<li><b>Interpreter:</b><br>
					Works for Linux/86, Linux/PPC, S390, StrongARM, SPARC, HPPA, SPARC v9</li>

					<li><a href="/contributing/asp-net.html"><b>ASP.NET:</b><br>
					Webforms and WebServices working</a></li>
	
					<li><a href="/using/gtk-sharp.html"><b>GTK#:</b><br>
					Released with Mono 1.0</a></li>
				</ul>
			</div>
		</div> <!-- End Right Nav -->
