				<div id="searchBoxTop"><!-- Comment is here to fix an IE DIV height display bug. jduncan --></div>
				<div id="searchBox">
					<div id="searchBoxInner">
						<form action="http://search.novell.com/NSearch/SearchServlet" method="get">
							<input name="server" value="novell" type="hidden" />
							<input name="theme" value="mono" type="hidden" />
							<input name="collection" value="mono" type="hidden" />
							<input name="noexpand" value="true" type="hidden" />
							search<br/>
							<input type="text" name="query0" style="width: 150px;" /><br />
							<input type="submit" name="submit" value="Submit" />
						</form>
					</div>
				</div>
				<div id="searchBoxBottom"></div>
