.\" 
.\" bush manual page.
.\" Author:
.\"   Gonzalo Paniagua Javier (gonzalo ximian.com)
.\"
.de Sp
.if t .sp .5v
.if n .sp
..
.TH Bush "Bush 0.0.1"
.SH NAME
bush \- A faked attempt on something.
.SH SYNOPSIS
.PP
.B bush [--message text]
.SH DESCRIPTION
\fIbush\fP is a dummy project provided as a sample on autotools usage.
.SH OPTIONS
.TP
.I "--message"
You can provide a text to be displayed when the button is clicked.
.SH SEE ALSO
.BR mono(1)


