// Generated by Cocoa# Glue Generator @ 07/04/2005 11:03:19

using System;
namespace Apple.Foundation {
    public enum _NSByteOrder {
        NS_UnknownByteOrder = 0,
        NS_LittleEndian = 1,
        NS_BigEndian = 2,
    }
}
